name: BookMoney
main: work.raru.spigot.book_money.Main
version: 0.1
author: ozraru
description: Convert bitween book and dollars.
depend: [Vault]
commands:
  bm:
    description: BookMoney Command
    aliases: [bookmoney]
    usage: |
      /bm create <amount>
      /bmc <amount>
      Example: /bm create 100 - Get a 100 dollars book, and pay 100 dollars.
      Example: /bmc 1000 - Get 10000 dollars book, and pay 10000 dollars.
      /bm use
      /bmu
      You must have MoneyBook in Mainhand
      Example: /bm use - If you have 100 dollars book in mainhand, you get 100 dollars.
  bmc:
    description: MoneyBook create Command
    aliases: [bm create,bookmoney create]
    usage: |
      /bm create <amount>
      /bmc <amount>
      Example: /bm create 100 - Get a 100 dollars book, and pay 100 dollars.
      Example: /bmc 1000 - Get 10000 dollars book, and pay 10000 dollars.
  bmu:
    description: MoneyBook use Command
    aliases: [bm use,bookmoney use]
    usage: |
      /bm use
      /bmu
      You must have MoneyBook in Mainhand
      Example: /bm use - If you have 100 dollars book in mainhand, you get 100 dollars.
permissions:
  book_money.*:
    description: Gives access to all BookMoney commands
    children:
      book_money.create: true
      book_money.use: true
  book_money.create:
    description: Allows create MoneyBook
    default: true
  book_money.use:
    description: Allows use MoneyBook
    default: true
  