name: AbilityChanger
main: work.raru.spigot.ability_changer.Main
version: 0.2
author: ozraru
description: Add ability change commands.
commands:
  fly:
    description: Enable fly
    aliases: [fly_on]
    permission: ability_changer.fly
    usage: |
      /fly [player]
      Example: /fly - Toggle fly you.
      Example: /fly ozraru - Toggle fly ozraru.
permissions:
  ability_changer.*:
    description: Gives access to all switch user commands
    children:
      ability_changer.fly: true
      ability_changer.fly.other: true
  ability_changer.fly:
    description: Allows you fly
    default: op
  ability_changer.fly.other:
    description: Allows you fly other
    default: op
  