name: RankManager
main: work.raru.spigot.rankmanager.Main
version: 0.1
author: ozraru
description: Link Minecraft-Discord.
depend: [Vault]
commands:
  rankmanager:
    description: RankManager Command
    aliases: [rm, rank_manager]
    usage: |
      /rm
      Example: /rm - Error!
  promote:
    description: Promote user
    aliases: [rmp]
    usage: |
      /promote <playerName/UUID> [World]
  demote:
    description: Demote user
    aliases: [rmp]
    usage: |
      /demote <playerName/UUID> [World]
  link:
    description: Generate token for Link to discord
    aliases: [discord]
    usage: |
      /link [MCID]
permissions:
  rankmanager.*:
    description: Gives access to all RankManager commands
    children:
      discordlink.a: true
  rankmanager.a:
    description: Allows open crafting table, if you have portable crafting table.
    default: true
  